# Server Port
server.port=8080

# Database Configuration (MySQL - Dev Local)
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/ssafy_db?serverTimezone=Asia/Seoul}
spring.datasource.username=${DB_USERNAME:quietjun}
spring.datasource.password=${DB_PASSWORD:dmstj@0205M}

# JPA Dev Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
